name: Publish Python Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pyyaml -r requirements.txt
        
    - name: 'Create env file'
      run: |
        touch .env
        echo OPENAI_API_TYPE='azure' >> .env
        echo OPENAI_API_VERSION='2024-08-01-preview' >> .env
        echo AZURE_OPENAI_ENDPOINT='https://llmevaluationset.openai.azure.com/' >> .env
        echo GPT_4_MODEL_DEPLOYMENT_NAME='gpt-4' >> .env
        echo GPT_35_MODEL_DEPLOYMENT_NAME='gpt-35-turbo-16k' >> .env
        echo EMBEDDING_DEPLOYMENT_NAME='text-embedding-ada-002' >> .env
        echo API_KEY=${{ secrets.AZURE_API_KEY }} >> .env

        cat .env  
    - name: Run tests
      run: |
        cd tests
        python -m unittest

    - name: Build package
      run: python -m build


    
    - name: Publish package to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
